import { useEffect, useRef, useState } from 'react'
import Icon from './Icon'

const formatTime = seconds => `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`

export default function CallRecorder({ client, clientId, notify }) {
  const [consent,setConsent]=useState(false);const [status,setStatus]=useState('idle');const [seconds,setSeconds]=useState(0);const [audioUrl,setAudioUrl]=useState('')
  const [transcript,setTranscript]=useState('');const [summary,setSummary]=useState('');const [history,setHistory]=useState([])
  const recorder=useRef(null);const stream=useRef(null);const chunks=useRef([])
  useEffect(()=>{setHistory(JSON.parse(localStorage.getItem(`calls:${clientId}`)||'[]'));setStatus('idle');setSeconds(0)},[clientId])
  useEffect(()=>{if(status!=='recording')return;const timer=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(timer)},[status])
  const start=async()=>{if(!consent)return;try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];recorder.current=new MediaRecorder(stream.current);recorder.current.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);recorder.current.onstop=()=>{const blob=new Blob(chunks.current,{type:'audio/webm'});setAudioUrl(URL.createObjectURL(blob));stream.current?.getTracks().forEach(t=>t.stop());const name=client?.name||'the client';setTranscript(`RM: Thank you for taking the time to speak today, ${name}. We reviewed the recent portfolio development and discussed how it relates to your priorities.\n\nClient: I appreciate the proactive update. Please send me the details and the proposed next steps.\n\nRM: I will share a concise review and arrange a follow-up conversation.`);setSummary(`Discussed the latest portfolio signal with ${name}. Client acknowledged the update and requested written details. Follow-up: share analysis and schedule a portfolio review.`);setStatus('review')};recorder.current.start();setSeconds(0);setStatus('recording')}catch(e){notify(`Microphone unavailable: ${e.message}`)}}
  const stop=()=>recorder.current?.stop()
  const save=()=>{const entry={id:Date.now(),date:new Date().toISOString(),duration:seconds,transcript,summary};const next=[entry,...history];localStorage.setItem(`calls:${clientId}`,JSON.stringify(next));setHistory(next);setStatus('idle');setConsent(false);notify('Call summary saved to local CRM timeline')}
  return <div className="call-workspace"><article className="card recorder-card"><div className="section-head"><div><span className="eyebrow">CONSENT-GATED RECORDING</span><h3>Record client call</h3></div><span className={`recording-state ${status}`}>{status==='recording'?<><i/>Recording {formatTime(seconds)}</>:status==='review'?'Ready to review':'Ready'}</span></div><label className="consent-check"><input type="checkbox" checked={consent} disabled={status==='recording'} onChange={e=>setConsent(e.target.checked)}/><span>I confirm that all participants have consented to this recording and transcription.</span></label>{status==='idle'&&<button className="record-button" disabled={!consent} onClick={start}><Icon name="mic"/>Start recording</button>}{status==='recording'&&<button className="stop-button" onClick={stop}><span/>Stop recording</button>}{status==='review'&&<div className="call-review">{audioUrl&&<audio controls src={audioUrl}/>}<label>Simulated transcript<textarea value={transcript} onChange={e=>setTranscript(e.target.value)}/></label><label>CRM call summary<textarea value={summary} onChange={e=>setSummary(e.target.value)}/></label><div><small>Transcript is simulated for the demo; recording remains in this browser session.</small><button className="primary-button" onClick={save}>Save call summary</button></div></div>}</article><article className="card call-history"><span className="eyebrow">RECENT CALL SUMMARIES</span>{history.map(call=><div key={call.id}><span className="call-icon"><Icon name="mic"/></span><div><strong>{new Date(call.date).toLocaleString()}</strong><p>{call.summary}</p><small>{formatTime(call.duration)} · Stored locally</small></div></div>)}{!history.length&&<p className="empty-copy">No recorded calls for this client yet.</p>}</article></div>
}
