import { useEffect, useState } from 'react'
import Icon from '../components/Icon'
import { api } from '../services/api'
import CallRecorder from '../components/CallRecorder'

const money = value => new Intl.NumberFormat('en-CH',{style:'currency',currency:'CHF',maximumFractionDigits:0}).format(value||0)

export default function ClientProfilePage({ clientId, navigate, notify }) {
  const [tab,setTab]=useState('dna');const [data,setData]=useState(null);const [loading,setLoading]=useState(true)
  const load=async()=>{if(!clientId)return;setLoading(true);const [client,dna,portfolio,alerts,messages]=await Promise.allSettled([api.client(clientId),api.dna(clientId),api.portfolio(clientId),api.alerts(clientId),api.messages(clientId)]);setData({client:client.value,dna:dna.value,portfolio:portfolio.value,alerts:alerts.value||[],messages:messages.value||[]});setLoading(false)}
  useEffect(()=>{load()},[clientId])
  const replacement=async issuer=>{try{const r=await api.replacement(clientId,issuer);notify(r.buy?`${issuer} → ${r.buy}`:r.message)}catch(e){notify(e.message)}}
  if(loading||!data)return <div className="loading-state">Loading complete client profile…</div>
  const dna=data.dna?.dna||{},notes=data.dna?.source_notes||[],portfolio=data.portfolio||{holdings:[]}
  return <div className="page-wrap"><section className="profile-hero"><div className="avatar profile-avatar">{data.client?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><span className="eyebrow">PRIVATE WEALTH CLIENT</span><h2>{data.client?.name}</h2><p>{data.client?.strategy} strategy · {money(portfolio.total_value_chf)} under management</p></div><button className="outline" onClick={()=>navigate('trust')}>Open Trust Navigator <Icon name="compass"/></button></section><div className="profile-tabs">{[['dna','Client DNA'],['portfolio','Portfolio'],['notes','CRM Notes'],['alerts','Alerts'],['messages','Messages'],['calls','Call Recorder']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}{id==='alerts'&&<b>{data.alerts.length}</b>}</button>)}</div>
  {tab==='dna'&&<div className="profile-grid"><article className="card profile-summary"><span className="eyebrow">COMMUNICATION STYLE</span><h3>{dna.communication_style||'Not extracted'}</h3><p>{dna.family_context||'No family context available.'}</p><div className="profile-facts"><div><small>RISK STYLE</small><strong>{dna.risk_style||'—'}</strong></div><div><small>STRATEGY</small><strong>{dna.strategy||data.client?.strategy}</strong></div></div></article><article className="card"><span className="eyebrow">VALUES</span><div className="chips">{(dna.values||[]).map(x=><span key={x}>{x}</span>)}</div><span className="eyebrow profile-label">RED FLAGS</span><div className="chips danger">{(dna.red_flags||[]).map(x=><span key={x}>{x}</span>)}</div></article><article className="card"><span className="eyebrow">AVOID</span><div className="chips danger">{(dna.avoid||[]).map(x=><span key={x}>{x}</span>)}</div><span className="eyebrow profile-label">PREFERRED SECTORS</span><div className="chips">{(dna.preferred_sectors||[]).map(x=><span key={x}>{x}</span>)}</div></article></div>}
  {tab==='portfolio'&&<article className="card portfolio-table"><div className="portfolio-row portfolio-head"><span>Holding</span><span>Sector</span><span>Current</span><span>Drift</span><span>Status</span><span>Action</span></div>{portfolio.holdings.map(h=><div className="portfolio-row" key={h.id}><div><strong>{h.issuer}</strong><small>{h.cio_rating} rated</small></div><span>{h.sector}</span><b>{money(h.current_value_chf)}</b><span>{h.drift_pct>0?'+':''}{h.drift_pct}%</span><b className={`allocation ${String(h.allocation_status).toLowerCase().replace(' ','-')}`}>{h.allocation_status}</b><button className="table-action" disabled={h.allocation_status!=='SELL'} onClick={()=>replacement(h.issuer)}>{h.allocation_status==='SELL'?'Suggest replacement':'—'}</button></div>)}</article>}
  {tab==='notes'&&<div className="timeline">{notes.map(note=><article key={note.id}><span/><div><small>{note.date}</small><p>{note.note}</p></div></article>)}</div>}
  {tab==='alerts'&&<div className="signal-feed">{data.alerts.map(a=><article className="alert-card" key={a.id}><span className={`alert-mark ${String(a.severity).toLowerCase()}`}><Icon name="alert"/></span><div className="alert-copy"><div><b className={`severity ${String(a.severity).toLowerCase()}`}>{a.severity}</b><small>{a.holding}</small></div><h3>{a.news_headline||a.alert_type}</h3><p>{a.reason}</p></div><button className="table-action" onClick={()=>replacement(a.holding)}>Suggest replacement</button></article>)}</div>}
  {tab==='messages'&&<div className="message-list">{data.messages.map(m=><article className="card" key={m.id}><div><b className="pill green">{m.tone}</b><small>{m.approved?'Approved':'Draft'} · {m.created_at}</small></div><pre>{m.content}</pre>{!m.approved&&<button className="primary-button" onClick={async()=>{await api.approveMessage(m.id);notify('Message approved');load()}}>Approve message</button>}</article>)}{!data.messages.length&&<div className="empty-state">No messages generated for this client.</div>}</div>}
  {tab==='calls'&&<CallRecorder client={data.client} clientId={clientId} notify={notify}/>} 
  </div>
}
