import { useEffect, useMemo, useState } from 'react'
import Icon from '../components/Icon'
import { api } from '../services/api'
import { prioritizeClients, rankNews } from '../utils/intelligenceModel'

export default function CommandCenterPage({ clients, setClientId, navigate, notify }) {
  const [news,setNews]=useState([]);const [alerts,setAlerts]=useState([]);const [live,setLive]=useState(true);const [updated,setUpdated]=useState(null);const [busy,setBusy]=useState(false)
  const load=async()=>{const [n,a]=await Promise.all([api.news(),api.allAlerts()]);setNews(n);setAlerts(a);setUpdated(new Date())}
  useEffect(()=>{load().catch(()=>{});if(!live)return;const timer=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(timer)},[live])
  const rankedNews=useMemo(()=>rankNews(news,alerts),[news,alerts]);const priorities=useMemo(()=>prioritizeClients(clients,alerts),[clients,alerts])
  const refresh=async()=>{setBusy(true);try{await api.refreshNews('Roche,Nestlé,NVIDIA',true);await load();notify('Live intelligence refreshed')}catch(e){notify(e.message)}finally{setBusy(false)}}
  return <div className="page-wrap command-page"><section className="command-hero"><div><div className="live-line"><span className={`live-indicator ${live?'on':''}`}/><b>{live?'LIVE INTELLIGENCE':'LIVE PAUSED'}</b><small>{updated?`Updated ${updated.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Connecting…'}</small></div><h2>RM Command Center</h2><p>Rank the news. Predict client impact. Know who needs you first.</p></div><div className="command-controls"><label><input type="checkbox" checked={live} onChange={e=>setLive(e.target.checked)}/>Auto-refresh</label><button className="primary-button" disabled={busy} onClick={refresh}><Icon name="news"/>{busy?'Refreshing…':'Refresh live news'}</button></div></section><section className="command-metrics"><article><span>REACT NOW</span><strong>{priorities.filter(c=>c.priority>=70).length}</strong><small>Priority clients</small></article><article><span>HIGH-IMPACT NEWS</span><strong>{rankedNews.filter(n=>n.score>=60).length}</strong><small>Events ranked 60+</small></article><article><span>CLIENTS AFFECTED</span><strong>{priorities.filter(c=>c.relatedAlerts).length}</strong><small>With open signals</small></article><article><span>REFRESH RATE</span><strong>30s</strong><small>When live is enabled</small></article></section><div className="command-grid"><article className="card priority-panel"><div className="section-head"><div><span className="eyebrow">CLIENT PRIORITIZATION</span><h3>Who should I react to?</h3></div><span className="model-label">AI-ranked</span></div><div className="priority-list">{priorities.map((client,index)=><button key={client.id} onClick={()=>{setClientId(client.id);navigate('profile')}}><b className="rank-number">{index+1}</b><span className="avatar small">{client.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><strong>{client.name}</strong><small>{client.reason}</small><em className={`mood ${client.moodTone}`}>Simulated mood: {client.mood}</em></div><div className="priority-score"><strong>{client.priority}</strong><small>priority</small></div><span className={`reaction ${client.priority>=70?'urgent':client.priority>=40?'review':''}`}>{client.action}</span></button>)}</div></article><article className="card ranked-news"><div className="section-head"><div><span className="eyebrow">RANKED LIVE NEWS</span><h3>Predicted client impact</h3></div></div>{rankedNews.slice(0,6).map((item,index)=><div className="ranked-news-item" key={item.id}><b>{index+1}</b><div><div><span className={`news-dot ${item.sentiment}`}/><strong>{item.headline}</strong></div><p>{item.prediction}</p><small>{item.direction} · {item.linkedClients} clients · {item.confidence}% confidence</small></div><span className="news-score">{item.score}</span></div>)}</article></div><p className="simulation-note"><Icon name="alert" size={14}/>Mood and impact predictions are AI simulations for RM decision support—not factual psychological or market forecasts.</p></div>
}
