import { useEffect, useMemo, useState } from 'react'
import Icon from '../components/Icon'
import { loadClientWorkspace } from '../services/api'
import { buildRelationshipProfile } from '../utils/relationshipScore'

function Gauge({ score }) {
  const radius=64,circumference=2*Math.PI*radius
  return <div className="gauge"><svg viewBox="0 0 160 160"><circle className="gauge-track" cx="80" cy="80" r={radius}/><circle className="gauge-value" cx="80" cy="80" r={radius} strokeDasharray={circumference} strokeDashoffset={circumference*(1-score/100)}/></svg><div className="gauge-copy"><strong>{score}</strong><span>out of 100</span></div></div>
}

function Trend({ values }) {
  const points=useMemo(()=>values.map((v,i)=>`${i*(300/(values.length-1))},${72-(v-25)*.75}`).join(' '),[values])
  return <div className="trend"><svg viewBox="0 0 300 76" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#207a58" stopOpacity=".22"/><stop offset="1" stopColor="#207a58" stopOpacity="0"/></linearGradient></defs><polygon points={`0,72 ${points} 300,72`} fill="url(#fade)"/><polyline points={points} fill="none" stroke="#207a58" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/></svg><div><span>90 days ago</span><span>Today</span></div></div>
}

export default function TrustNavigatorPage({ clients,clientId,navigate,notify }) {
  const [profile,setProfile]=useState(null);const [loading,setLoading]=useState(false)
  useEffect(()=>{if(!clientId)return;let active=true;setLoading(true);loadClientWorkspace(clientId).then(workspace=>{if(active)setProfile(buildRelationshipProfile(clients.find(c=>c.id===clientId),workspace))}).finally(()=>active&&setLoading(false));return()=>{active=false}},[clientId,clients])
  if(!clientId)return <div className="empty-state page-empty"><Icon name="users"/><h3>No client selected</h3><p>Connect the backend to load the client book.</p></div>
  if(loading||!profile)return <div className="loading-state">Building relationship baseline…</div>
  const delta=profile.score-profile.previousScore
  return <>
    <section className="client-strip"><div className="avatar large">{profile.initials}</div><div className="client-title"><div><h2>{profile.name}</h2><span className="live"><i/>Backend data</span></div><p>{profile.segment}<b/>Assets under management <strong>{profile.aum}</strong><b/>Last contact <strong>{profile.lastContact}</strong></p></div><button className="outline" onClick={()=>navigate('dna')}>View Client DNA <Icon name="arrow"/></button></section>
    <section className="hero-grid"><article className="score-card"><div className="card-head"><div><span className="eyebrow">RELATIONSHIP HEALTH</span><span className="info">i</span></div><span className="pill green">{profile.status}</span></div><div className="score-layout"><Gauge score={profile.score}/><div className="score-story"><div className="momentum"><span><Icon name="up"/></span><div><small>RELATIONSHIP MOMENTUM</small><strong>{profile.momentum}</strong></div><b>{delta} pts</b></div><p>{profile.summary}</p></div></div></article><article className="momentum-card"><div className="card-head"><div><span className="eyebrow">MOMENTUM</span><span className="info">i</span></div><select><option>90 days</option></select></div><div className="compare"><div><small>THEN</small><strong>{profile.previousScore}</strong></div><span><Icon name="up"/>{delta}</span><div><small>NOW</small><strong>{profile.score}</strong></div></div><Trend values={profile.trend}/><small className="baseline-note">Baseline only — the existing API has no score history</small></article></section>
    <section className="content-grid"><div><article className="card signals"><div className="section-head"><div><span className="eyebrow">HEALTH COMPOSITION</span><h3>What shapes this score</h3></div><span className="updated">Calculated in frontend</span></div>{profile.dimensions.map(d=><div className="signal" key={d.label}><div className="signal-meta"><div><strong>{d.label}</strong><span>{d.weight}% weight</span></div><b>{d.value}</b></div><div className="bar"><i style={{width:`${d.value}%`}}/></div><small>{d.detail}</small></div>)}</article><article className="card drivers"><div className="section-head"><div><span className="eyebrow">EXPLAINABILITY</span><h3>What’s driving the relationship</h3></div></div><div className="driver-cols"><div><h4 className="positive"><Icon name="up"/>Positive drivers</h4>{profile.positive.map(([a,b,c])=><div className="driver" key={a}><span className="driver-icon good"><Icon name="check"/></span><div><strong>{a}</strong><small>{b}</small></div><b className="gain">{c}</b></div>)}</div><div><h4 className="risk"><Icon name="alert"/>Risk drivers</h4>{profile.risks.map(([a,b,c])=><div className="driver" key={a}><span className="driver-icon warn"><Icon name="alert"/></span><div><strong>{a}</strong><small>{b}</small></div><b className="risk-tag">{c}</b></div>)}</div></div></article></div><aside className="recommendation card"><div className="recommend-top"><span className="spark"><Icon name="spark"/></span><div><span className="eyebrow">RELATIONSHIP GPS</span><h3>Recommended next moves</h3></div></div><p>Based on the current backend portfolio, messaging and signal data.</p><div className="stage"><span>CURRENT STAGE</span><strong>{profile.status}</strong><small>Score range {profile.scoreRange}</small></div><div className="actions">{profile.actions.map((a,i)=><button className={`action ${a.type}`} key={a.title} onClick={()=>notify(`${a.title} added to plan`)}><span>{i+1}</span><div><b>{a.tag}</b><strong>{a.title}</strong><small>{a.text}</small></div><Icon name="arrow"/></button>)}</div><button className="plan-btn" onClick={()=>notify('Relationship plan created')}>Create relationship plan <Icon name="arrow"/></button><small className="ai-note"><Icon name="spark" size={14}/>Frontend recommendation · RM remains in control</small></aside></section>
  </>
}
