"""
reasoning_agent.py - The core matching engine.

For every client:
  Client DNA + Portfolio Holdings + News Events + CIO Recs → Alerts

Uses a rule-based relevance scorer first, then calls LLM only for explanation.
This keeps determinism high and LLM costs low.
"""
import json
import re
import unicodedata
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import database as db
from services.llm_service import call_llm_json
from agents.crm_agent import extract_client_dna


def _normalise_name(value: str) -> str:
    """Normalise company names while tolerating common Excel/encoding variants."""
    value = (value or "").replace("Ã©", "é").replace("Ã¤", "ä").replace("Ã¶", "ö").replace("Ã¼", "ü")
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode().lower()
    value = re.sub(r"\b(ag|sa|ltd|corp|corporation|inc|holding|holdings|group|plc|nv)\b", " ", value)
    return " ".join(re.findall(r"[a-z0-9]+", value))


def _meaningful_words(values: list[str]) -> set[str]:
    return {word for value in values for word in re.findall(r"[a-z]+", _normalise_name(value)) if len(word) >= 4}


def calculate_relevance_score(client_dna: dict, holding: dict, news: dict) -> int:
    """
    Rule-based relevance score 0-100.
    High score = strong match between news, holding, and client DNA.
    """
    score = 0

    values = client_dna.get("values", [])
    red_flags = client_dna.get("red_flags", [])
    avoid = client_dna.get("avoid", [])
    theme = _normalise_name(news.get("theme") or "")
    headline = _normalise_name(news.get("headline") or "")
    company = _normalise_name(news.get("company") or "")
    issuer = _normalise_name(holding.get("issuer") or "")

    # A news alert must concern an asset the client actually owns. Previously,
    # DNA theme matches were applied to every holding, creating thousands of rows.
    company_matches_holding = bool(company and issuer and (company in issuer or issuer in company))
    if not company_matches_holding:
        return 0
    score += 35

    # News theme matches client values
    if _meaningful_words(values) & set(theme.split()):
        score += 15

    # News headline matches a red flag
    if _meaningful_words(red_flags) & set(headline.split()):
        score += 25

    # News matches avoid list
    if _meaningful_words(avoid) & set(headline.split()):
        score += 20

    # Severity multiplier
    severity = (news.get("severity") or "low").lower()
    if severity == "high":
        score = int(score * 1.2)
    elif severity == "low":
        score = int(score * 0.8)

    return min(score, 100)


def determine_alert_type(client_dna: dict, holding: dict, news: dict) -> str:
    values = [v.lower() for v in client_dna.get("values", [])]
    sentiment = (news.get("sentiment") or "neutral").lower()
    theme = (news.get("theme") or "").lower()

    if sentiment == "positive":
        return "Positive opportunity"
    if any(word in theme for word in ["parkinson", "cancer", "research", "medical"]):
        return "Personal conflict"
    if any(word in theme for word in ["esg", "sustainability", "deforestation", "labour"]):
        return "ESG conflict"
    if (holding.get("cio_rating") or "").upper() == "SELL":
        return "CIO conflict"
    return "Portfolio conflict"


def explain_alert(client_dna: dict, holding: dict, news: dict, alert_type: str) -> str:
    """Ask LLM to write a one-paragraph human-readable explanation."""
    prompt = f"""
You are a Swiss private banking AI. Write ONE concise paragraph (max 60 words)
explaining why this news event is personally relevant to this client.

Alert type: {alert_type}
Client values: {client_dna.get('values', [])}
Client red flags: {client_dna.get('red_flags', [])}
Affected holding: {holding.get('issuer')} ({holding.get('sector')})
News headline: {news.get('headline')}
News theme: {news.get('theme')}
News sentiment: {news.get('sentiment')}

Return JSON: {{"explanation": "<your one paragraph>"}}
"""
    try:
        result = call_llm_json(prompt)
        return result.get("explanation", "Alert generated by rule engine.")
    except Exception:
        return f"This news event about {news.get('company', 'a portfolio holding')} may conflict with the client's personal values and investment priorities."


def run_analysis_for_client(client_id: str, min_score: int = 30) -> list[dict]:
    """
    Run the full reasoning pipeline for one client.
    Returns list of created alert dicts.
    """
    client = db.get_client(client_id)
    if not client:
        return []

    try:
        dna = extract_client_dna(client_id)
    except Exception as e:
        print(f"DNA extraction failed for {client_id}: {e}")
        return []

    holdings = db.get_holdings(client_id)
    news_events = db.get_all_news()
    created_alerts = []

    for news in news_events:
        for holding in holdings:
            score = calculate_relevance_score(dna, holding, news)
            if score < min_score:
                continue

            if db.alert_exists(client_id, holding["issuer"], news["id"]):
                continue

            alert_type = determine_alert_type(dna, holding, news)
            severity = "High" if score >= 70 else "Medium" if score >= 45 else "Low"

            # Generate LLM explanation
            reason = explain_alert(dna, holding, news, alert_type)
            recommended_action = _recommend_action(alert_type, holding, dna, client["strategy"])

            alert_id = db.insert_alert(
                client_id=client_id,
                alert_type=alert_type,
                severity=severity,
                holding=holding["issuer"],
                news_id=news["id"],
                reason=reason,
                recommended_action=recommended_action,
                confidence=score
            )

            # Another analysis request may have inserted this exact signal while
            # the explanation was being generated. The unique index wins safely.
            if alert_id is None:
                continue

            created_alerts.append({
                "id": alert_id,
                "client_id": client_id,
                "alert_type": alert_type,
                "severity": severity,
                "holding": holding["issuer"],
                "reason": reason,
                "recommended_action": recommended_action,
                "confidence": score,
                "news_headline": news["headline"]
            })

    return created_alerts


def run_analysis_for_all_clients(min_score: int = 30) -> dict:
    """Run the analysis pipeline for every client."""
    clients = db.get_all_clients()
    results = {}
    for client in clients:
        alerts = run_analysis_for_client(client["id"], min_score=min_score)
        results[client["id"]] = alerts
        print(f"[OK] {client['name']}: {len(alerts)} alerts generated")
    return results


def _recommend_action(alert_type: str, holding: dict, dna: dict, mandate: str) -> str:
    sector = holding.get("sector", "this sector")
    issuer = holding.get("issuer", "this holding")

    if alert_type == "Positive opportunity":
        return f"Consider increasing allocation to {issuer} – aligns with client values."
    elif alert_type == "CIO conflict":
        return f"Review {issuer}: CIO rating has changed. Consider CIO-approved replacement in {sector}."
    else:
        return f"Review {issuer} for personal alignment conflict. Consider CIO-approved replacement in {sector}."
