"""
reasoning_agent.py - The core matching engine.

For every client:
  Client DNA + Portfolio Holdings + News Events + CIO Recs → Alerts

Uses a rule-based relevance scorer first, then calls LLM only for explanation.
This keeps determinism high and LLM costs low.
"""
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import database as db
from services.llm_service import call_llm_json
from agents.crm_agent import extract_client_dna


def calculate_relevance_score(client_dna: dict, holding: dict, news: dict) -> int:
    """
    Rule-based relevance score 0-100.
    High score = strong match between news, holding, and client DNA.
    """
    score = 0

    values = [v.lower() for v in client_dna.get("values", [])]
    red_flags = [r.lower() for r in client_dna.get("red_flags", [])]
    avoid = [a.lower() for a in client_dna.get("avoid", [])]
    theme = (news.get("theme") or "").lower()
    headline = (news.get("headline") or "").lower()
    company = (news.get("company") or "").lower()
    issuer = (holding.get("issuer") or "").lower()

    # Company directly matches holding
    if company and company in issuer or issuer in company:
        score += 35

    # News theme matches client values
    for value in values:
        if any(word in theme for word in value.split()):
            score += 15
            break

    # News headline matches a red flag
    for flag in red_flags:
        if any(word in headline for word in flag.split()):
            score += 25
            break

    # News matches avoid list
    for item in avoid:
        if any(word in headline for word in item.split()):
            score += 20
            break

    # Severity multiplier
    severity = (news.get("severity") or "low").lower()
    if severity == "high":
        score = int(score * 1.2)
    elif severity == "low":
        score = int(score * 0.8)

    return min(score, 100)


def determine_alert_type(client_dna: dict, holding: dict, news: dict) -> str:
    values = [v.lower() for v in client_dna.get("values", [])]
    sentiment = (news.get("sentiment") or "neutral").lower()
    theme = (news.get("theme") or "").lower()

    if sentiment == "positive":
        return "Positive opportunity"
    if any(word in theme for word in ["parkinson", "cancer", "research", "medical"]):
        return "Personal conflict"
    if any(word in theme for word in ["esg", "sustainability", "deforestation", "labour"]):
        return "ESG conflict"
    if (holding.get("cio_rating") or "").upper() == "SELL":
        return "CIO conflict"
    return "Portfolio conflict"


def explain_alert(client_dna: dict, holding: dict, news: dict, alert_type: str) -> str:
    """Ask LLM to write a one-paragraph human-readable explanation."""
    prompt = f"""
You are a Swiss private banking AI. Write ONE concise paragraph (max 60 words)
explaining why this news event is personally relevant to this client.

Alert type: {alert_type}
Client values: {client_dna.get('values', [])}
Client red flags: {client_dna.get('red_flags', [])}
Affected holding: {holding.get('issuer')} ({holding.get('sector')})
News headline: {news.get('headline')}
News theme: {news.get('theme')}
News sentiment: {news.get('sentiment')}

Return JSON: {{"explanation": "<your one paragraph>"}}
"""
    try:
        result = call_llm_json(prompt)
        return result.get("explanation", "Alert generated by rule engine.")
    except Exception:
        return f"This news event about {news.get('company', 'a portfolio holding')} may conflict with the client's personal values and investment priorities."


def run_analysis_for_client(client_id: str, min_score: int = 30) -> list[dict]:
    """
    Run the full reasoning pipeline for one client.
    Returns list of created alert dicts.
    """
    client = db.get_client(client_id)
    if not client:
        return []

    try:
        dna = extract_client_dna(client_id)
    except Exception as e:
        print(f"DNA extraction failed for {client_id}: {e}")
        return []

    holdings = db.get_holdings(client_id)
    news_events = db.get_all_news()
    created_alerts = []

    for news in news_events:
        for holding in holdings:
            score = calculate_relevance_score(dna, holding, news)
            if score < min_score:
                continue

            alert_type = determine_alert_type(dna, holding, news)
            severity = "High" if score >= 70 else "Medium" if score >= 45 else "Low"

            # Generate LLM explanation
            reason = explain_alert(dna, holding, news, alert_type)
            recommended_action = _recommend_action(alert_type, holding, dna, client["strategy"])

            alert_id = db.insert_alert(
                client_id=client_id,
                alert_type=alert_type,
                severity=severity,
                holding=holding["issuer"],
                news_id=news["id"],
                reason=reason,
                recommended_action=recommended_action,
                confidence=score
            )

            created_alerts.append({
                "id": alert_id,
                "client_id": client_id,
                "alert_type": alert_type,
                "severity": severity,
                "holding": holding["issuer"],
                "reason": reason,
                "recommended_action": recommended_action,
                "confidence": score,
                "news_headline": news["headline"]
            })

    return created_alerts


def run_analysis_for_all_clients(min_score: int = 30) -> dict:
    """Run the analysis pipeline for every client."""
    clients = db.get_all_clients()
    results = {}
    for client in clients:
        alerts = run_analysis_for_client(client["id"], min_score=min_score)
        results[client["id"]] = alerts
        print(f"✓ {client['name']}: {len(alerts)} alerts generated")
    return results


def _recommend_action(alert_type: str, holding: dict, dna: dict, mandate: str) -> str:
    sector = holding.get("sector", "this sector")
    issuer = holding.get("issuer", "this holding")

    if alert_type == "Positive opportunity":
        return f"Consider increasing allocation to {issuer} – aligns with client values."
    elif alert_type == "CIO conflict":
        return f"Review {issuer}: CIO rating has changed. Consider CIO-approved replacement in {sector}."
    else:
        return f"Review {issuer} for personal alignment conflict. Consider CIO-approved replacement in {sector}."
